/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.filter-container[_ngcontent-%COMP%] {\n    min-width: 250px;\n    max-width: 350px;\n    border: 1px solid #ddd;\n}\n.filter[_ngcontent-%COMP%] {\n\n}\n.filter[_ngcontent-%COMP%]   .header[_ngcontent-%COMP%]{\n\n}\n.filter[_ngcontent-%COMP%]   .header[_ngcontent-%COMP%]   .text[_ngcontent-%COMP%]{\n\n}'];